### ISSUE TITLE
[ERROR] default - ReplyError: NOGROUP No such key '/logs/activity' or consumer group 'job.log' in XREADGROUP with GROUP option

### ISSUE THREAD

**Issue by BornTKill** [ferrumgate/rest.portal#1]
Dear,

i have configured Ferrumgate with 3 nodes (one cluster) and after a moment on my 2 slaves (redis) I have this errors.

```
ferrumgate --all-logs

[2023-11-08T09:31:32.893] [ERROR] default - ReplyError: NOGROUP No such key '/logs/activity' or consumer group 'job.log' in XREADGROUP with GROUP option
    at parseError (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'job.log',
      'fCtwzbpFb8B9ACHF',
      'COUNT',
      '10000',
      'BLOCK',
      '10000',
      'STREAMS',
      '/logs/activity',
      '>'
    ]
  }
}
```

After restarting ferrumgate the error disappears.
Thank you.

**Comment by ferrumgate** [comment]
Please check ,It dissapered forever or continues some time.

**Comment by BornTKill** [comment]
No more error since yesterday.

**Comment by BornTKill** [comment]
To be sûre. You want me to check logs on each machine When login on each machine portal ?

**Comment by ferrumgate** [comment]
yes please

**Comment by ferrumgate** [comment]
I updated job.log image
please on each machine
docker pull ferrumgate/job.log:1.12.0 
ferrumgate --restart

will solve problem.

**Comment by BornTKill** [comment]
Dear,

Thank you. I have updated. Let you know.

**Comment by BornTKill** [comment]
Dear,

Works ! Thank you again :)

**Comment by BornTKill** [comment]
Ho shit, it happens again.

```
[2023-12-13T07:47:43.045] [ERROR] default - ReplyError: NOGROUP No such key '/logs/activity/svc' or consumer group 'job.log' in XREADGROUP with GROUP option
    at parseError (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'job.log',
      'Xdul2v1SmcPihPZ3',
      'COUNT',
      '10000',
      'BLOCK',
      '1000',
      'STREAMS',
      '/logs/activity/svc',
      '>'
    ]
  }
}
[2023-12-13T07:47:43.048] [ERROR] default - ReplyError: NOGROUP No such key '/logs/activity' or consumer group 'job.log' in XREADGROUP with GROUP option
    at parseError (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'job.log',
      'EmFo0vaHUa6t2s1y',
      'COUNT',
      '10000',
      'BLOCK',
      '10000',
      'STREAMS',
      '/logs/activity',
      '>'
    ]
  }
}
[2023-12-13T07:47:43.069] [ERROR] default - ReplyError: NOGROUP No such key '/logs/audit' or consumer group 'job.log' in XREADGROUP with GROUP option
    at parseError (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'job.log',
      'GWcTSTIXNS9RS51b',
      'COUNT',
      '10000',
      'BLOCK',
      '10000',
      'STREAMS',
      '/logs/audit',
      '>'
    ]
  }
}
[2023-12-13T07:47:43.103] [ERROR] default - ReplyError: NOGROUP No such key '/logs/device' or consumer group 'job.log' in XREADGROUP with GROUP option
    at parseError (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/usr/src/rest.portal/build/src/node_modules/redis-parser/lib/parser.js:302:14) {
  command: {
    name: 'xreadgroup',
    args: [
      'GROUP',
      'job.log',
      'Ua3DNtK6C7HL4E58',
      'COUNT',
      '10000',
      'BLOCK',
      '10000',
      'STREAMS',
      '/logs/device',
      '>'
    ]
  }
}
```

**Comment by ferrumgate** [comment]
are you using cluster? how many networks did you created

**Comment by BornTKill** [comment]
I have 1 cluster with 3 nodes and only 1 network. (3 gateways attached to it)

**Comment by BornTKill** [comment]
note that all clients are connected to master node only. (my DNS is pointing to master only for now because I tried round robin DNS but clients was not able to connect on slaves)

**Comment by ferrumgate** [comment]
The problem is about making cluster. There was an error about creating redis cluster

    `docker run -ti redis:7-bullseye redis-cli -h $HOST_A_CLUSTER_IP`  ->>>>> this is wrong 

We published the fixed documentation. You need to backup your config. then reset all machines and create cluster again. 


`ferrumgate --uninstall` 
will delete everything. 
then install it again 
`curl  https://raw.githubusercontent.com/ferrumgate/secure.install/master/install.sh | sh`
upload backup config
then create cluster again.

**Comment by BornTKill** [comment]
> The problem is about making cluster. There was an error about creating redis cluster
> 
> ```
> `docker run -ti redis:7-bullseye redis-cli -h $HOST_A_CLUSTER_IP`  ->>>>> this is wrong 
> ```
> 
> We published the fixed documentation. You need to backup your config. then reset all machines and create cluster again.
> 
> `ferrumgate --uninstall` will delete everything. then install it again `curl https://raw.githubusercontent.com/ferrumgate/secure.install/master/install.sh | sh` upload backup config then create cluster again.

OK I will do this.

**Comment by BornTKill** [comment]
> > note that all clients are connected to master node only. (my DNS is pointing to master only for now because I tried round robin DNS but clients was not able to connect on slaves)
> 
> It must be configured like below ![gateway drawio (1)](https://private-user-images.githubusercontent.com/102880959/290159767-697a8ef8-d897-42cd-8fe7-2f274b5061f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzE3MjUsIm5iZiI6MTcwMjQ3MTQyNSwicGF0aCI6Ii8xMDI4ODA5NTkvMjkwMTU5NzY3LTY5N2E4ZWY4LWQ4OTctNDJjZC04ZmU3LTJmMjc0YjUwNjFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMjQzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTlkMDI5NmRmOWU5NDZhNDMxNDBhODlkYzZlNjA1NTcwMDg4NTlhNTgyOTdmMWViZDRhNGM2NTFiYmRlZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cs75euQeauGPflitwRt57ToWHGDga2nf5n2AnKNJn1M)

Instead of using LoadBalancer, can we use DNS round robin to avoid having a "SPOF" ?

**Comment by BornTKill** [comment]
Are you sure I have to recreate the cluster ? I am use to configure redis-cluster so please find my configuration.

```
root@prod-ferrumgate-01:~# ferrumgate --show-cluster-config

**** current peers *****
prod-ferrumgate-03/10.10.7.59:54321/169.254.254.59/c000c5133b3a0dc6374ef95820312eccdfa839bc00beaa8636c4bcaae40d2d0a
prod-ferrumgate-02/10.10.7.58:54321/169.254.254.58/b06dc18a2dd213c87e8af1c4e09236795794994b4acdc5100cad7d49d9d7de7d

**** current host *****
host: prod-ferrumgate-01
ip: 169.254.254.57
port: 54321
pubKey: 456b9753084f75032b37f42d88e3fd60f426b0ba908650d58e0fae38b7a55a56

**** commands **********
PEER="prod-ferrumgate-01/public_ip:port/169.254.254.57/456b9753084f75032b37f42d88e3fd60f426b0ba908650d58e0fae38b7a55a56"
ferrumgate --add-cluster-peer $PEER
wg set wgferrum peer RWuXUwhPdQMrN/QtiOP9YPQmsLqQhlDVjg+uOLelWlY= allowed-ips 169.254.254.57


root@prod-ferrumgate-01:~# docker run -ti redis:7-bullseye redis-cli -h 169.254.254.57
169.254.254.57:6379> auth XXXXX
OK
169.254.254.57:6379> role
1) "master"
2) (integer) 93422173
3) 1) 1) "169.254.254.58"
      2) "6379"
      3) "93422031"
   2) 1) "169.254.254.59"
      2) "6379"
      3) "93422031"

root@prod-ferrumgate-02:~# ferrumgate --show-cluster-config

**** current peers *****
prod-ferrumgate-03/10.10.7.59:54321/169.254.254.59/c000c5133b3a0dc6374ef95820312eccdfa839bc00beaa8636c4bcaae40d2d0a
prod-ferrumgate-01/10.10.7.57:54321/169.254.254.57/456b9753084f75032b37f42d88e3fd60f426b0ba908650d58e0fae38b7a55a56

**** current host *****
host: prod-ferrumgate-02
ip: 169.254.254.58
port: 54321
pubKey: b06dc18a2dd213c87e8af1c4e09236795794994b4acdc5100cad7d49d9d7de7d

**** commands **********
PEER="prod-ferrumgate-02/public_ip:port/169.254.254.58/b06dc18a2dd213c87e8af1c4e09236795794994b4acdc5100cad7d49d9d7de7d"
ferrumgate --add-cluster-peer $PEER
wg set wgferrum peer sG3Bii3SE8h+ivHE4JI2eVeUmUtKzcUQDK19SdnX3n0= allowed-ips 169.254.254.58


root@prod-ferrumgate-02:~# docker run -ti redis:7-bullseye redis-cli -h 169.254.254.58
169.254.254.58:6379> auth XXXXX
OK
169.254.254.58:6379> role
1) "slave"
2) "169.254.254.57"
3) (integer) 6379
4) "connected"
5) (integer) 94202270


root@prod-ferrumgate-03:~# ferrumgate --show-cluster-config

**** current peers *****
prod-ferrumgate-02/10.10.7.58:54321/169.254.254.58/b06dc18a2dd213c87e8af1c4e09236795794994b4acdc5100cad7d49d9d7de7d
prod-ferrumgate-01/10.10.7.57:54321/169.254.254.57/456b9753084f75032b37f42d88e3fd60f426b0ba908650d58e0fae38b7a55a56

**** current host *****
host: prod-ferrumgate-03
ip: 169.254.254.59
port: 54321
pubKey: c000c5133b3a0dc6374ef95820312eccdfa839bc00beaa8636c4bcaae40d2d0a

**** commands **********
PEER="prod-ferrumgate-03/public_ip:port/169.254.254.59/c000c5133b3a0dc6374ef95820312eccdfa839bc00beaa8636c4bcaae40d2d0a"
ferrumgate --add-cluster-peer $PEER
wg set wgferrum peer wADFEzs6DcY3TvlYIDEuzN+oObwAvqqGNsS8quQNLQo= allowed-ips 169.254.254.59

root@prod-ferrumgate-03:~# docker run -ti redis:7-bullseye redis-cli -h 169.254.254.59
169.254.254.59:6379> auth XXXXX
OK
169.254.254.59:6379> role
1) "slave"
2) "169.254.254.57"
3) (integer) 6379
4) "connected"
5) (integer) 94503994
```

**Comment by ferrumgate** [comment]
> > > note that all clients are connected to master node only. (my DNS is pointing to master only for now because I tried round robin DNS but clients was not able to connect on slaves)
> > 
> > 
> > It must be configured like below ![gateway drawio (1)](https://private-user-images.githubusercontent.com/102880959/290159767-697a8ef8-d897-42cd-8fe7-2f274b5061f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzE3MjUsIm5iZiI6MTcwMjQ3MTQyNSwicGF0aCI6Ii8xMDI4ODA5NTkvMjkwMTU5NzY3LTY5N2E4ZWY4LWQ4OTctNDJjZC04ZmU3LTJmMjc0YjUwNjFmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxM1QxMjQzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTlkMDI5NmRmOWU5NDZhNDMxNDBhODlkYzZlNjA1NTcwMDg4NTlhNTgyOTdmMWViZDRhNGM2NTFiYmRlZjdhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Cs75euQeauGPflitwRt57ToWHGDga2nf5n2AnKNJn1M)
> 
> Instead of using LoadBalancer, can we use DNS round robin to avoid having a "SPOF" ?
> 
> ztna.company.com --> X.X.X.A --> Host A ztna.company.com --> X.X.X.B --> Host B ztna.company.com --> X.X.X.C --> Host C

yes. It should work

**Comment by ferrumgate** [comment]
If you can just fix redis cluster. you can do it. No need to recreate cluster.

**Comment by BornTKill** [comment]
Dear,

My redis cluster is working.
My 2 slaves are connected to master.
Ferrumgate is configured to point to master (ferrumgate --set-redis-master) bu when trying to establish a connection on a ferrum gateway that is on a slave I am rejected.

```
ferrum_generate_tunnel_id: ferrum tunnel sid generated 7hnjmsTYYsqSGlrucNiwyKBxQil6tbAp1eXJs8AWyEYkLqiOb4naiydZ96CEzGsm
ferrum_redis_test: ferrum redis reply error READONLY You can't write against a read only replica.
PAM: Authentication failure for ferrum from X.X.X.X
PAM: Authentication failure for ferrum from X.X.X.X
PAM: Authentication failure for ferrum from X.X.X.X
```

It is as if my B and C hosts are connected locally and not on host A (redis master)

**Comment by ferrumgate** [comment]
this error comes from configuration file error /etc/ferrumgate/env
for fixing it 
on each machine , execute this command, and set master ip that starts with 169.254.254.*
`ferrumgate --set-redis-master`

if you don't know master machine ip , on master host  execcute     
`ferrumgate --show-cluster-config`

then on all machines 
`ferrumgate --restart`

**Comment by BornTKill** [comment]
```
root@prod-ferrumgate-01:~# ferrumgate --set-redis-master
current master is: 169.254.254.57
enter ip: 

root@prod-ferrumgate-02:~# ferrumgate --set-redis-master
current master is: 169.254.254.57
enter ip: 

root@prod-ferrumgate-03:~# ferrumgate --set-redis-master
current master is: 169.254.254.57
enter ip: 
```

it's already done.

**Comment by ferrumgate** [comment]
on each host check /etc/ferrumgate/env file, 
CLUSTER_REDIS_MASTER variable, it must be setted

**Comment by BornTKill** [comment]
Sorry for bothering you.

```
root@prod-ferrumgate-01:~# grep CLUSTER_REDIS_MASTER /etc/ferrumgate/env
CLUSTER_REDIS_MASTER=169.254.254.57

root@prod-ferrumgate-02:~# grep CLUSTER_REDIS_MASTER /etc/ferrumgate/env
CLUSTER_REDIS_MASTER=169.254.254.57

root@prod-ferrumgate-03:~# grep CLUSTER_REDIS_MASTER /etc/ferrumgate/env 
CLUSTER_REDIS_MASTER=169.254.254.57
```

**Comment by ferrumgate** [comment]
Not a problem.
what is values 
REDIS_HOST
REDIS_PROXY_HOST
REDIS_HA_HOST
REDIS_HOST_SSH

**Comment by BornTKill** [comment]
```
root@prod-ferrumgate-01:~# grep REDIS /etc/ferrumgate/env
REDIS_HOST=redis:6379
REDIS_HA_HOST=redis-ha:6379
REDIS_HOST_SSH=redis-ha#6379
REDIS_PROXY_HOST=redis-ha:6379
REDIS_LOCAL_HOST=redis-local:6379
REDIS_INTEL_HOST=redis:6379
CLUSTER_REDIS_MASTER=169.254.254.57
CLUSTER_REDIS_QUORUM=2

root@prod-ferrumgate-02:~# grep REDIS /etc/ferrumgate/env
REDIS_HOST=redis:6379
REDIS_HA_HOST=redis-ha:6379
REDIS_HOST_SSH=redis-ha#6379
REDIS_PROXY_HOST=redis-ha:6379
REDIS_LOCAL_HOST=redis-local:6379
REDIS_INTEL_HOST=redis:6379
CLUSTER_REDIS_MASTER=169.254.254.57
CLUSTER_REDIS_QUORUM=2

root@prod-ferrumgate-03:~# grep REDIS /etc/ferrumgate/env
REDIS_HOST=redis:6379
REDIS_HA_HOST=redis-ha:6379
REDIS_HOST_SSH=redis-ha#6379
REDIS_PROXY_HOST=redis-ha:6379
REDIS_LOCAL_HOST=redis-local:6379
REDIS_INTEL_HOST=redis:6379
CLUSTER_REDIS_MASTER=169.254.254.57
CLUSTER_REDIS_QUORUM=2
```

**Comment by ferrumgate** [comment]
ok. I found the problem I think. 
on /etc/ferrumgate folder 
there are files *.gateway.yaml, on each file
there is a line
image: "??PRIVATE_REGISTRY/ferrumgate/secure.server.quic:1.1.0"
*********
environment:
      - REDIS_HOST=${REDIS_HOST}
change  this redis_host line to

environment:
      - REDIS_HOST=${REDIS_PROXY_HOST}
      
curly braces
{REDIS_HOST} -> ${REDIS_PROXY_HOST}

**Comment by BornTKill** [comment]
Do you think that it may be because of this 

```
root@prod-ferrumgate-01:~# ferrumgate --set-config redis
host: redis:6379
pass:

root@prod-ferrumgate-02:~# ferrumgate --set-config redis
host: redis:6379
pass:


root@prod-ferrumgate-03:~# ferrumgate --set-config redis
host: redis:6379
pass:
```

`Have to be redis-ha:6379 ?`

**Comment by ferrumgate** [comment]
ignore previous message that includes REDIS_HOST

**Comment by BornTKill** [comment]
> ignore previous message that includes REDIS_HOST

So I have to consider my message ?

**Comment by ferrumgate** [comment]
ok. I found the problem I think.
on /etc/ferrumgate folder
there are files *.gateway.yaml, on each file
there is a line
image: "??PRIVATE_REGISTRY/ferrumgate/secure.server.quic:1.1.0"

environment:
- REDIS_HOST=${REDIS_HOST}
change this redis_host line to

environment:
- REDIS_HOST=${REDIS_PROXY_HOST}

curly braces
{REDIS_HOST} -> ${REDIS_PROXY_HOST

please test this one.

**Comment by BornTKill** [comment]
Dear,

It's now :)
Will ping you if I have new issue. Thank you very much.
