### ISSUE TITLE
LDAPS

### ISSUE THREAD

**Issue by jmessenger51** [ferrumgate/rest.portal#5]
Is there a way to enable LDAPS? my cyber team is concerned about a potentially publically exposed system not using LDAPS for credential transport.

**Comment by hamzakilic** [comment]
we are using  this project  https://www.passportjs.org/packages/passport-ldapauth/ , to support ldap authentication.
please enter host like below and test it
`ldaps://ad.corporate.com:636`

**Comment by jmessenger51** [comment]
with LDAPS, the key encryption is with a private cert, In passportjs it calls out the ldaps certificate location:
`
var fs = require('fs');

var opts = {
  server: {
    url: 'ldaps://ad.corporate.com:636',
    bindDN: 'cn=non-person,ou=system,dc=corp,dc=corporate,dc=com',
    bindCredentials: 'secret',
    searchBase: 'dc=corp,dc=corporate,dc=com',
    searchFilter: '(&(objectcategory=person)(objectclass=user)(|(samaccountname={{username}})(mail={{username}})))',
    searchAttributes: ['displayName', 'mail'],
    tlsOptions: {
      ca: [
        fs.readFileSync('/path/to/root_ca_cert.crt')
      ]
    }
  }
};
` 
However, I don't see a way through the GUI to upload the cert. I can push it via SSH but its not clear the best method.

**Comment by hamzakilic** [comment]
Are you using a self generated certificate?

**Comment by jmessenger51** [comment]
our LDAP server is also an internal PKI

**Comment by jmessenger51** [comment]
> yes, our LDAP server is also an internal PKI
> 
> Out plan is to use letsencrypt for the public facing TLS, LDAPS for encrypting the authentication traffic.

I tried following: 
https://ferrumgate.com/docs/configuration/settings/pki/
and copying the root CA to the directory but thats not working.

**Comment by hamzakilic** [comment]
No it does not work, we need to add new fields to UI. We are working on a release, I will try to add it.
